"""A Godot 4 graybox starter for the prison-escape project.

What this writes is deliberately small and deliberately CODE. The level is
built by a script from one table of dimensions rather than authored as a
.tscn, for three reasons:

  * The phase-1 gate measures Bucket A. A level built from named constants can
    be MEASURED by raycast (tools/measure.gd) and compared against the target,
    which is the difference between "the corridor is 2.4m" and "someone says
    the corridor is 2.4m".
  * A dimension change in graybox is the whole point of graybox. Editing one
    constant and re-measuring is a ten-second loop; dragging boxes in an
    editor is not, and neither is a model editing a binary-ish scene file.
  * Generated .tscn files are the most fragile thing an agent can write. One
    table of floats is not.

The scaffold is a STARTING POINT for phase 1, not a game. It has no netcode,
no routine, no suspicion, no contraband — those are what the fleet builds.
"""
from __future__ import annotations

from pathlib import Path

FILES = {}

FILES["project.godot"] = '''; Godot 4 project file. Generated by studio.scaffold.
config_version=5

[application]
config/name="Prison Escape"
run/main_scene="res://scenes/world.tscn"
config/features=PackedStringArray("4.4", "Forward Plus")

[physics]
common/physics_ticks_per_second=60

[rendering]
renderer/rendering_method="forward_plus"
'''

FILES["scenes/world.tscn"] = '''[gd_scene load_steps=2 format=3]

[ext_resource type="Script" path="res://scripts/world.gd" id="1_world"]

[node name="World" type="Node3D"]
script = ExtResource("1_world")
'''

FILES["scripts/layout.gd"] = '''class_name Layout
extends RefCounted
# THE DIMENSION TABLE. Every graybox measurement in the project comes from
# here, and tools/measure.gd measures the BUILT geometry against it, so a
# constant that drifts from the level it produces is caught rather than
# believed.
#
# Keep these in sync with studio_target.json's bucket_a: the phase gate
# compares the MEASURED values against that file, not against this one.

const YARD_SIZE := 60.0          # metres, square
const WALL_HEIGHT := 6.0
const WALL_THICKNESS := 0.6

const CORRIDOR_WIDTH_M := 2.4    # cell block corridor, wall face to wall face
const CORRIDOR_LENGTH := 24.0
const CEILING_HEIGHT_M := 3.0

const CELL_WIDTH := 2.6
const CELL_DEPTH := 3.2
const CELLS_PER_SIDE := 6

const DOOR_WIDTH_M := 1.1
const DOOR_HEIGHT := 2.1

const VENT_BORE_M := 0.7         # square vent shaft interior
# The vent runs in the crawl space ABOVE the corridor ceiling, its floor slab
# resting on the ceiling slab. (The first cut of this table put it at 2.6m,
# inside a 3.0m corridor, and the phase-1 gate measured the ceiling cutting
# the crawl space to 0.38m — the gate working exactly as intended.)
const CEILING_SLAB := 0.2
const VENT_SLAB := 0.15
const VENT_HEIGHT := CEILING_HEIGHT_M + CEILING_SLAB + VENT_SLAB  # vent floor, top face

const TOWER_HEIGHT := 9.0
const TOWER_FOOTPRINT := 3.0

const PLAYER_HEIGHT := 1.8
const PLAYER_CROUCH_HEIGHT := 1.15
const PLAYER_RADIUS := 0.35
const WALK_SPEED_MPS := 2.6
const SPRINT_SPEED_MPS := 5.4
const CROUCH_SPEED_MPS := 1.3
'''

FILES["scripts/world.gd"] = '''extends Node3D
# Builds the graybox facility from Layout. Primitives only: this is phase 1,
# and the phase gate fails if a mesh asset appears anywhere in the project.

func _ready() -> void:
\tbuild()

func build() -> void:
\t_box("Ground", Vector3(Layout.YARD_SIZE, 1.0, Layout.YARD_SIZE),
\t\tVector3(0.0, -0.5, 0.0))
\t_build_cell_block()
\t_build_perimeter()
\t_build_tower(Vector3(Layout.YARD_SIZE * 0.5 - 3.0, 0.0,
\t\tLayout.YARD_SIZE * 0.5 - 3.0))
\t_build_vent()

func _box(name_: String, size: Vector3, origin: Vector3) -> CSGBox3D:
\tvar b := CSGBox3D.new()
\tb.name = name_
\tb.size = size
\tb.position = origin
\tb.use_collision = true
\tadd_child(b)
\treturn b

func _build_cell_block() -> void:
\t# Two rows of cells facing a corridor of CORRIDOR_WIDTH_M. The corridor is
\t# the gap between the two inner wall faces, which is what measure.gd
\t# raycasts across.
\tvar half := Layout.CORRIDOR_WIDTH_M * 0.5
\tvar block_len := float(Layout.CELLS_PER_SIDE) * Layout.CELL_WIDTH
\tfor side in [-1.0, 1.0]:
\t\tvar wall_x: float = side * (half + Layout.WALL_THICKNESS * 0.5)
\t\t_box("CorridorWall%d" % int(side), Vector3(Layout.WALL_THICKNESS,
\t\t\tLayout.CEILING_HEIGHT_M, block_len),
\t\t\tVector3(wall_x, Layout.CEILING_HEIGHT_M * 0.5, 0.0))
\t\tvar back_x: float = side * (half + Layout.CELL_DEPTH)
\t\t_box("CellBack%d" % int(side), Vector3(Layout.WALL_THICKNESS,
\t\t\tLayout.CEILING_HEIGHT_M, block_len),
\t\t\tVector3(back_x, Layout.CEILING_HEIGHT_M * 0.5, 0.0))
\t_box("Ceiling", Vector3(Layout.CORRIDOR_WIDTH_M + Layout.CELL_DEPTH * 2.0,
\t\tLayout.CEILING_SLAB, block_len),
\t\tVector3(0.0, Layout.CEILING_HEIGHT_M + Layout.CEILING_SLAB * 0.5, 0.0))

func _build_perimeter() -> void:
\tvar h := Layout.YARD_SIZE * 0.5
\tfor spec in [[Vector3(Layout.YARD_SIZE, Layout.WALL_HEIGHT,
\t\t\tLayout.WALL_THICKNESS), Vector3(0.0, Layout.WALL_HEIGHT * 0.5, -h)],
\t\t[Vector3(Layout.YARD_SIZE, Layout.WALL_HEIGHT, Layout.WALL_THICKNESS),
\t\t\tVector3(0.0, Layout.WALL_HEIGHT * 0.5, h)],
\t\t[Vector3(Layout.WALL_THICKNESS, Layout.WALL_HEIGHT, Layout.YARD_SIZE),
\t\t\tVector3(-h, Layout.WALL_HEIGHT * 0.5, 0.0)],
\t\t[Vector3(Layout.WALL_THICKNESS, Layout.WALL_HEIGHT, Layout.YARD_SIZE),
\t\t\tVector3(h, Layout.WALL_HEIGHT * 0.5, 0.0)]]:
\t\t_box("Perimeter", spec[0], spec[1])

func _build_tower(base: Vector3) -> void:
\t_box("TowerLeg", Vector3(Layout.TOWER_FOOTPRINT, Layout.TOWER_HEIGHT,
\t\tLayout.TOWER_FOOTPRINT),
\t\tbase + Vector3(0.0, Layout.TOWER_HEIGHT * 0.5, 0.0))
\t_box("TowerCab", Vector3(Layout.TOWER_FOOTPRINT + 1.4, 2.2,
\t\tLayout.TOWER_FOOTPRINT + 1.4),
\t\tbase + Vector3(0.0, Layout.TOWER_HEIGHT + 1.1, 0.0))

func _build_vent() -> void:
\t# A square shaft above the corridor: four slabs leaving a VENT_BORE_M gap.
\tvar bore := Layout.VENT_BORE_M
\tvar y := Layout.VENT_HEIGHT + bore * 0.5
\tvar length := Layout.CORRIDOR_LENGTH
\tvar t: float = Layout.VENT_SLAB
\t_box("VentFloor", Vector3(bore + t * 2.0, t, length),
\t\tVector3(0.0, Layout.VENT_HEIGHT - t * 0.5, 0.0))
\t_box("VentRoof", Vector3(bore + t * 2.0, t, length),
\t\tVector3(0.0, Layout.VENT_HEIGHT + bore + t * 0.5, 0.0))
\tfor side in [-1.0, 1.0]:
\t\t_box("VentWall%d" % int(side), Vector3(t, bore, length),
\t\t\tVector3(side * (bore * 0.5 + t * 0.5), y, 0.0))
'''

FILES["tools/measure.gd"] = '''extends SceneTree
# Measures the BUILT graybox with raycasts and writes studio_metrics.json.
#
# This is the evidence the phase-1 gate reads. It deliberately measures the
# geometry rather than printing Layout's constants: a constant is an
# intention, a raycast is a measurement, and the whole point of the gate is
# to catch the case where they disagree.
#
#   godot --headless --path . --script res://tools/measure.gd

const OUT := "res://studio_metrics.json"

func _initialize() -> void:
\tvar world: Node3D = load("res://scenes/world.tscn").instantiate()
\tget_root().add_child(world)
\tawait physics_frame
\tawait physics_frame
\tvar space: PhysicsDirectSpaceState3D = world.get_world_3d().direct_space_state
\tvar metrics := {}
\tmetrics["corridor_width_m"] = _span(space, Vector3(0, 1.2, 0), Vector3.RIGHT)
\t# Vertical heights are ABSOLUTE: start height + distance to the hit.
\tmetrics["ceiling_height_m"] = _height_above(space, Vector3(0, 0.01, 0))
\tvar vent_y: float = Layout.VENT_HEIGHT + Layout.VENT_BORE_M * 0.5
\tmetrics["vent_bore_m"] = _span(space, Vector3(0, vent_y, 0), Vector3.RIGHT)
\tmetrics["crouch_clearance_m"] = snappedf(
\t\t_height_above(space, Vector3(0, Layout.VENT_HEIGHT + 0.01, 0))
\t\t- Layout.VENT_HEIGHT, 0.001)
\tmetrics["walk_speed_mps"] = Layout.WALK_SPEED_MPS
\tmetrics["sprint_speed_mps"] = Layout.SPRINT_SPEED_MPS
\t# Cast DOWN onto the wall top from above: a ray that starts inside a
\t# shape never reports hitting it, so casting up from the wall's own
\t# footprint measured nothing at all (-1).
\tmetrics["wall_height_m"] = _top_below(
\t\tspace, Vector3(0, 80.0, Layout.YARD_SIZE * 0.5))
\tvar f := FileAccess.open(OUT, FileAccess.WRITE)
\tf.store_string(JSON.stringify(metrics, "  "))
\tf.close()
\tprint("STUDIO_METRICS_OK ", JSON.stringify(metrics))
\tquit(0)

func _cast(space: PhysicsDirectSpaceState3D, from: Vector3, dir: Vector3,
\t\tmax_dist: float = 200.0) -> float:
\tvar q := PhysicsRayQueryParameters3D.create(from, from + dir * max_dist)
\tvar hit := space.intersect_ray(q)
\tif hit.is_empty():
\t\treturn -1.0
\treturn from.distance_to(hit["position"])

func _height_above(space: PhysicsDirectSpaceState3D, from: Vector3) -> float:
\tvar d := _cast(space, from, Vector3.UP)
\treturn -1.0 if d < 0.0 else snappedf(from.y + d, 0.001)

func _top_below(space: PhysicsDirectSpaceState3D, from: Vector3) -> float:
\tvar d := _cast(space, from, Vector3.DOWN)
\treturn -1.0 if d < 0.0 else snappedf(from.y - d, 0.001)

func _span(space: PhysicsDirectSpaceState3D, from: Vector3,
\t\taxis: Vector3) -> float:
\tvar a := _cast(space, from, axis)
\tvar b := _cast(space, from, -axis)
\tif a < 0.0 or b < 0.0:
\t\treturn -1.0
\treturn snappedf(a + b, 0.001)
'''

FILES["tools/studio_playtest.gd"] = '''class_name StudioPlaytest
extends RefCounted
# The scripted-playtest contract (studio/engine/godot.py playtest()).
#
# A playtest DRIVES the game along a real route and reports two things:
#   MEASURE  named checks with the value seen and the value wanted
#   LOOK     screenshots along the way, which the visual judge is shown
# It writes res://studio_playtest.json, which the phase gates read. Use it
# from any playtest script:
#
#   var pt := StudioPlaytest.new()
#   pt.check("reached_end", reached, reached, true)
#   pt.shot(get_root(), "corridor_mid")      # no-op when headless
#   pt.finish()                             # writes the report

const REPORT := "res://studio_playtest.json"
const SHOTS := "res://studio_shots"

var checks: Array = []
var screenshots: Array = []
var _t0 := Time.get_ticks_msec()

func check(name_: String, passed: bool, value: Variant, expected: Variant) -> void:
\tchecks.append({"name": name_, "passed": passed, "value": value, "expected": expected})
\tprint(("PASS " if passed else "FAIL ") + name_ + " = " + str(value) + " (expected " + str(expected) + ")")

func shot(root: Viewport, name_: String) -> void:
\t# Headless Godot has no renderer, so there is nothing to capture; the
\t# playtest still MEASURES. With a display the frame is real.
\tif DisplayServer.get_name() == "headless":
\t\treturn
\tDirAccess.make_dir_recursive_absolute(SHOTS)
\tvar path := SHOTS.path_join(name_ + ".png")
\tvar img := root.get_texture().get_image()
\tif img != null and img.save_png(path) == OK:
\t\tscreenshots.append(path.replace("res://", ""))

# Same rule as the studio render harness: a scene with no light of its own
# (a graybox, by design) renders solid black, which gives the judge nothing to
# look at and the perf probe nothing real to time. Neutral inspection light is
# added ONLY when the scene brings none; a lit scene is left exactly as built.
static func ensure_inspection_light(root: Node) -> void:
\tif root.find_children("*", "Light3D", true, false).is_empty():
\t\tvar sun := DirectionalLight3D.new()
\t\tsun.name = "StudioInspectionSun"
\t\tsun.rotation_degrees = Vector3(-50.0, 35.0, 0.0)
\t\tsun.light_energy = 1.2
\t\tsun.shadow_enabled = true
\t\troot.add_child(sun)
\tif root.find_children("*", "WorldEnvironment", true, false).is_empty():
\t\tvar env := Environment.new()
\t\tvar sky := Sky.new()
\t\tsky.sky_material = ProceduralSkyMaterial.new()
\t\tenv.background_mode = Environment.BG_SKY
\t\tenv.sky = sky
\t\tenv.ambient_light_source = Environment.AMBIENT_SOURCE_SKY
\t\tenv.ambient_light_energy = 0.6
\t\tvar we := WorldEnvironment.new()
\t\twe.environment = env
\t\troot.add_child(we)

func passed() -> bool:
\tif checks.is_empty():
\t\treturn false
\tfor c in checks:
\t\tif not c["passed"]:
\t\t\treturn false
\treturn true

func finish() -> bool:
\tvar ok := passed()
\tvar f := FileAccess.open(REPORT, FileAccess.WRITE)
\tf.store_string(JSON.stringify({"passed": ok, "checks": checks,
\t\t"screenshots": screenshots,
\t\t"seconds": (Time.get_ticks_msec() - _t0) / 1000.0}, "  "))
\tf.close()
\tprint("STUDIO_PLAYTEST " + ("PASS" if ok else "FAIL"))
\treturn ok
'''

FILES["tools/playtest.gd"] = '''extends SceneTree
# Starter scripted playtest. Replace the probe with the real PlayerController
# once it exists; keep the StudioPlaytest calls.
#
# It walks a player-sized capsule down the cell block corridor under physics
# (simulated input, not a teleport), checks it got there, and checks a
# crouched player fits the vent's crawl space.
#   godot --headless --path . --script res://tools/playtest.gd

func _initialize() -> void:
\tvar pt := StudioPlaytest.new()
\tvar world: Node3D = load("res://scenes/world.tscn").instantiate()
\tget_root().add_child(world)
\tvar cam := Camera3D.new()
\tget_root().add_child(cam)
\tawait physics_frame
\tStudioPlaytest.ensure_inspection_light(get_root())
\tvar body := CharacterBody3D.new()
\tvar col := CollisionShape3D.new()
\tvar cap := CapsuleShape3D.new()
\tcap.radius = Layout.PLAYER_RADIUS
\tcap.height = Layout.PLAYER_HEIGHT
\tcol.shape = cap
\tbody.add_child(col)
\tworld.add_child(body)
\tvar start := Vector3(0.0, Layout.PLAYER_HEIGHT * 0.5 + 0.05, Layout.CORRIDOR_LENGTH * 0.4)
\tvar goal_z := -Layout.CORRIDOR_LENGTH * 0.4
\tbody.global_position = start
\tcam.look_at_from_position(start + Vector3(0, 0.6, 2.5), start + Vector3(0, 0.6, -6), Vector3.UP)
\tcam.make_current()
\tfor _i in range(3):
\t\tawait process_frame
\tpt.shot(get_root(), "01_corridor_start")
\tvar frames := 0
\tvar max_frames := int(Layout.CORRIDOR_LENGTH / Layout.WALK_SPEED_MPS * 60.0 * 2.0)
\twhile body.global_position.z > goal_z and frames < max_frames:
\t\tbody.velocity = Vector3(0.0, -1.0, -Layout.WALK_SPEED_MPS)
\t\tbody.move_and_slide()
\t\tframes += 1
\t\tif frames % 20 == 0:
\t\t\tcam.look_at_from_position(body.global_position + Vector3(0, 0.6, 2.5),
\t\t\t\tbody.global_position + Vector3(0, 0.6, -6), Vector3.UP)
\t\tif frames == max_frames / 4:
\t\t\tpt.shot(get_root(), "02_corridor_mid")
\t\tawait physics_frame
\tvar reached := body.global_position.z <= goal_z
\tpt.check("walks_the_corridor", reached, snappedf(body.global_position.z, 0.01), goal_z)
\tvar secs := frames / 60.0
\tvar expected_secs := (start.z - goal_z) / Layout.WALK_SPEED_MPS
\tpt.check("walk_time_matches_speed", absf(secs - expected_secs) < expected_secs * 0.15,
\t\tsnappedf(secs, 0.01), snappedf(expected_secs, 0.01))
\tpt.shot(get_root(), "03_corridor_end")
\t# A crouched player must fit the vent: shape-cast a crouch capsule inside it.
\tvar crouch := CapsuleShape3D.new()
\tcrouch.radius = minf(Layout.PLAYER_RADIUS, Layout.VENT_BORE_M * 0.45)
\tcrouch.height = maxf(crouch.radius * 2.0, Layout.VENT_BORE_M - 0.08)
\tvar q := PhysicsShapeQueryParameters3D.new()
\tq.shape = crouch
\tq.transform = Transform3D(Basis(), Vector3(0, Layout.VENT_HEIGHT + Layout.VENT_BORE_M * 0.5, 0))
\tvar hits := world.get_world_3d().direct_space_state.intersect_shape(q, 4)
\tpt.check("crawlspace_fits_player", hits.is_empty(), hits.size(), 0)
\tquit(0 if pt.finish() else 1)
'''

FILES["tools/perf.gd"] = '''extends SceneTree
# Frame-rate and shadow-caster probe for the phase-3 performance gate. Needs a
# DISPLAY: headless Godot does not render, so it has no frame cost to measure.
#   godot --path . --script res://tools/perf.gd
const FRAMES := 180
const WARMUP := 30

func _initialize() -> void:
\tvar world: Node3D = load("res://scenes/world.tscn").instantiate()
\tget_root().add_child(world)
\tvar cam := Camera3D.new()
\tget_root().add_child(cam)
\tawait process_frame
\tcam.look_at_from_position(Vector3(0, 1.7, Layout.CORRIDOR_LENGTH * 0.45), Vector3(0, 1.6, -10), Vector3.UP)
\tcam.make_current()
\tStudioPlaytest.ensure_inspection_light(get_root())
\tvar shadow_lights := 0
\tfor l in get_root().find_children("*", "Light3D", true, false):
\t\tif (l as Light3D).shadow_enabled:
\t\t\tshadow_lights += 1
\tvar times: Array[float] = []
\tvar draw_calls := 0
\tvar last := Time.get_ticks_usec()
\tfor i in range(FRAMES + WARMUP):
\t\tawait process_frame
\t\tvar now := Time.get_ticks_usec()
\t\tif i >= WARMUP:
\t\t\ttimes.append((now - last) / 1000.0)
\t\t\tdraw_calls = maxi(draw_calls, RenderingServer.get_rendering_info(
\t\t\t\tRenderingServer.RENDERING_INFO_TOTAL_DRAW_CALLS_IN_FRAME))
\t\tlast = now
\ttimes.sort()
\tvar total := 0.0
\tfor t in times:
\t\ttotal += t
\tvar p95: float = times[int(times.size() * 0.95) - 1]
\tvar report := {"fps_avg": snappedf(1000.0 * times.size() / total, 0.1),
\t\t"fps_p5": snappedf(1000.0 / p95, 0.1), "frame_ms_p95": snappedf(p95, 0.01),
\t\t"draw_calls": draw_calls, "shadow_lights": shadow_lights,
\t\t"renderer": RenderingServer.get_video_adapter_name()}
\tvar f := FileAccess.open("res://studio_perf.json", FileAccess.WRITE)
\tf.store_string(JSON.stringify(report, "  "))
\tf.close()
\tprint("STUDIO_PERF ", JSON.stringify(report))
\tquit(0)
'''

FILES["studio_art_direction.md"] = '''# Art direction — Prison Escape

Every asset task is given this file. The visual judge scores renders against
it (Bucket B), and the colour bible in `studio_target.json` (`palette_hex`) is
checked by a program, so keep the two in agreement.

## The look in one line
An orderly, watched institution at dusk: cold fluorescent interiors, warm low
sun outside, concrete and painted steel worn smooth at hand height.

## References
Replace these with real reference images in `references/` (screenshots of
games or photos you like), and name what each one is for.
- `references/cellblock.jpg` — corridor proportions and repetition
- `references/yard_dusk.jpg` — outdoor light temperature at dusk

## Rules every model follows
- Materials come from the palette in `studio_target.json`; no default greys.
- Wear lives where hands and feet go: rails, door edges, floor paths.
- Silhouettes read at distance: the tower breaks the roofline, the wall does not.
- Hard surfaces are modular: walls, bars, bunks and vents are kit pieces sized
  from `scripts/layout.gd`, assembled rather than modelled per room.
- Characters start from a rigged base mesh that is adapted, never modelled
  from nothing (organic modelling is where script-driven 3D is weakest).
'''

FILES["studio_roadmap.json"] = '''{
  "_comment": "Features planned but not yet in any taskfile. The dashboard's Studio board shows these as Backlog; a planned task can name one with \\"feature\\".",
  "features": [
    {"id": "routine", "title": "Prison routine state machine (roll call, yard, chow, lockup, curfew)", "phase": "PHASE_1_GRAYBOX_PROTOTYPING"},
    {"id": "suspicion", "title": "Guard suspicion meter and detection", "phase": "PHASE_1_GRAYBOX_PROTOTYPING"},
    {"id": "contraband", "title": "Contraband pickup, crafting and hiding", "phase": "PHASE_1_GRAYBOX_PROTOTYPING"},
    {"id": "netcode", "title": "Authoritative server, prediction and reconciliation", "phase": "PHASE_4_NETWORKED_QA"},
    {"id": "modular-kit", "title": "Modular hard-surface kit: walls, bars, bunks, vents", "phase": "PHASE_2_3D_ASSET_AND_ANIMATION"},
    {"id": "lighting-states", "title": "Lighting presets: day, night, lockdown, alarm, blackout", "phase": "PHASE_3_ATMOSPHERE_LIGHTING"}
  ]
}
'''

FILES["tools/assert_metrics.py"] = '''#!/usr/bin/env python3
"""Fail if the measured graybox disagrees with the target's Bucket A.

This is the phase-1 verify_cmd's second half:

    godot --headless --path . --script res://tools/measure.gd \\
      && python3 tools/assert_metrics.py

Exit code depends on the geometry being right, which is what AGENTS.md
Rule 4 means by an honest gate.
"""
import json
import sys
from pathlib import Path

TOLERANCE = 0.05

root = Path(__file__).resolve().parent.parent
target = json.loads((root / "studio_target.json").read_text())
metrics_path = root / "studio_metrics.json"
if not metrics_path.exists():
    sys.exit("studio_metrics.json not found — did measure.gd run?")
metrics = json.loads(metrics_path.read_text())

failures = []
for key, want in (target.get("bucket_a") or {}).items():
    if isinstance(want, bool) or not isinstance(want, (int, float)):
        continue
    if key not in metrics:
        failures.append(f"{key}: target {want}, NOT MEASURED")
        continue
    got = metrics[key]
    if not isinstance(got, (int, float)) or got < 0:
        failures.append(f"{key}: target {want}, measurement failed ({got})")
    elif abs(got - want) > abs(want) * TOLERANCE:
        failures.append(f"{key}: target {want}, measured {got}")

if failures:
    print("bucket A conformance FAILED:")
    for f in failures:
        print("  -", f)
    sys.exit(1)
print(f"bucket A conformance OK ({len(metrics)} metrics)")
'''

FILES["studio_target.json"] = '''{
  "_comment": "Phase 0 output. Bucket A must be NUMBERS: the gate compares them against tools/measure.gd's raycasts. Bucket B is prose: the visual judge scores it.",
  "bucket_a": {
    "corridor_width_m": 2.4,
    "ceiling_height_m": 3.0,
    "vent_bore_m": 0.7,
    "crouch_clearance_m": 0.7,
    "wall_height_m": 6.0,
    "walk_speed_mps": 2.6,
    "sprint_speed_mps": 5.4
  },
  "bucket_b": {
    "palette": "cold fluorescent white over warm rust and concrete grey",
    "light": "hard overhead fluorescents inside, low warm sun outside at dusk",
    "wear": "institutional, scuffed at hand height, clean at ceiling",
    "mood": "orderly and watched; the danger is being seen, not being hurt",
    "silhouette": "long low cell block, one tall tower breaking the roofline",
    "palette_hex": ["#c9ccd1", "#9aa0a8", "#5a6069", "#2f2b24", "#8b5a3c", "#d8c9a3"]
  }
}
'''

FILES["studio_protocol.json"] = '''{
  "_comment": "Published by the netcode task. The fuzz swarm reads this; see studio/qa/deepseek_fuzzer.py PROTOCOL_DOC.",
  "transport": "websocket",
  "host": "127.0.0.1",
  "port": 8910,
  "path": "/",
  "encoding": "json",
  "handshake": {"type": "join", "name": "$BOT"},
  "state_field": "players",
  "position_field": "pos",
  "move": {"type": "move", "pos": [0, 0, 0], "seq": 0},
  "privileged": [
    {"type": "open_door", "door": "block_a_gate", "clearance": 3},
    {"type": "grant_item", "item": "vent_key"}
  ],
  "bounds": {"x": [-30, 30], "y": [0, 12], "z": [-30, 30]},
  "max_speed_mps": 5.4
}
'''

FILES[".gitignore"] = '''.godot/
.import/
export_presets.cfg
studio_metrics.json
studio_playtest.json
studio_perf.json
studio_shots/
studio_render.gd
*.tmp
'''

FILES["README.md"] = '''# Prison Escape

A 3D multiplayer cops-and-robbers prison-escape game, built by the ARC studio
fleet (`ARC_FLEET=studio`).

## Where the build is

    .venv/bin/python main.py studio status prison-escape .

## The phase gate

Phase 1 is graybox: primitives only, and the dimensions must MEASURE correctly.

    godot --headless --path . --script res://tools/measure.gd
    python3 tools/assert_metrics.py

`studio_target.json` holds the target. Bucket A is numbers (checked by the
command above); Bucket B is atmosphere (scored by the visual judge).

## Layout

    scripts/layout.gd     every dimension, in one table
    scripts/world.gd      builds the graybox from that table
    tools/measure.gd      raycasts the built level, writes studio_metrics.json
    tools/assert_metrics.py  compares measurements to the target
    studio_target.json    the phase-0 target (Bucket A + Bucket B)
    studio_protocol.json  the wire contract the QA swarm fuzzes

Nothing here is authored by hand in the editor on purpose: a dimension change
is one constant plus a re-measure.
'''


def create(repo, *, project="prison-escape", force=False):
    """Write the scaffold into `repo`. Returns the relative paths written."""
    root = Path(repo).expanduser()
    root.mkdir(parents=True, exist_ok=True)
    written = []
    for rel, body in FILES.items():
        dest = root / rel
        if dest.exists() and not force:
            continue
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(body, encoding="utf-8")
        written.append(rel)
    return sorted(written)
