"""A Godot 4 graybox starter for the prison-escape project.

What this writes is deliberately small and deliberately CODE. The level is
built by a script from one table of dimensions rather than authored as a
.tscn, for three reasons:

  * The phase-1 gate measures Bucket A. A level built from named constants can
    be MEASURED by raycast (tools/measure.gd) and compared against the target,
    which is the difference between "the corridor is 2.4m" and "someone says
    the corridor is 2.4m".
  * A dimension change in graybox is the whole point of graybox. Editing one
    constant and re-measuring is a ten-second loop; dragging boxes in an
    editor is not, and neither is a model editing a binary-ish scene file.
  * Generated .tscn files are the most fragile thing an agent can write. One
    table of floats is not.

The scaffold is a STARTING POINT for phase 1, not a game. It has no netcode,
no routine, no suspicion, no contraband — those are what the fleet builds.
"""
from __future__ import annotations

from pathlib import Path

FILES = {}

FILES["project.godot"] = '''; Godot 4 project file. Generated by studio.scaffold.
config_version=5

[application]
config/name="Prison Escape"
run/main_scene="res://scenes/world.tscn"
config/features=PackedStringArray("4.4", "Forward Plus")

[physics]
common/physics_ticks_per_second=60

[rendering]
renderer/rendering_method="forward_plus"
'''

FILES["scenes/world.tscn"] = '''[gd_scene load_steps=2 format=3]

[ext_resource type="Script" path="res://scripts/world.gd" id="1_world"]

[node name="World" type="Node3D"]
script = ExtResource("1_world")
'''

FILES["scripts/layout.gd"] = '''class_name Layout
extends RefCounted
# THE DIMENSION TABLE. Every graybox measurement in the project comes from
# here, and tools/measure.gd measures the BUILT geometry against it, so a
# constant that drifts from the level it produces is caught rather than
# believed.
#
# Keep these in sync with studio_target.json's bucket_a: the phase gate
# compares the MEASURED values against that file, not against this one.

const YARD_SIZE := 60.0          # metres, square
const WALL_HEIGHT := 6.0
const WALL_THICKNESS := 0.6

const CORRIDOR_WIDTH_M := 2.4    # cell block corridor, wall face to wall face
const CORRIDOR_LENGTH := 24.0
const CEILING_HEIGHT_M := 3.0

const CELL_WIDTH := 2.6
const CELL_DEPTH := 3.2
const CELLS_PER_SIDE := 6

const DOOR_WIDTH_M := 1.1
const DOOR_HEIGHT := 2.1

const VENT_BORE_M := 0.7         # square vent shaft interior
const VENT_HEIGHT := 2.6         # height of the vent floor above the corridor floor

const TOWER_HEIGHT := 9.0
const TOWER_FOOTPRINT := 3.0

const PLAYER_HEIGHT := 1.8
const PLAYER_CROUCH_HEIGHT := 1.15
const PLAYER_RADIUS := 0.35
const WALK_SPEED_MPS := 2.6
const SPRINT_SPEED_MPS := 5.4
const CROUCH_SPEED_MPS := 1.3
'''

FILES["scripts/world.gd"] = '''extends Node3D
# Builds the graybox facility from Layout. Primitives only: this is phase 1,
# and the phase gate fails if a mesh asset appears anywhere in the project.

func _ready() -> void:
\tbuild()

func build() -> void:
\t_box("Ground", Vector3(Layout.YARD_SIZE, 1.0, Layout.YARD_SIZE),
\t\tVector3(0.0, -0.5, 0.0))
\t_build_cell_block()
\t_build_perimeter()
\t_build_tower(Vector3(Layout.YARD_SIZE * 0.5 - 3.0, 0.0,
\t\tLayout.YARD_SIZE * 0.5 - 3.0))
\t_build_vent()

func _box(name_: String, size: Vector3, origin: Vector3) -> CSGBox3D:
\tvar b := CSGBox3D.new()
\tb.name = name_
\tb.size = size
\tb.position = origin
\tb.use_collision = true
\tadd_child(b)
\treturn b

func _build_cell_block() -> void:
\t# Two rows of cells facing a corridor of CORRIDOR_WIDTH_M. The corridor is
\t# the gap between the two inner wall faces, which is what measure.gd
\t# raycasts across.
\tvar half := Layout.CORRIDOR_WIDTH_M * 0.5
\tvar block_len := float(Layout.CELLS_PER_SIDE) * Layout.CELL_WIDTH
\tfor side in [-1.0, 1.0]:
\t\tvar wall_x := side * (half + Layout.WALL_THICKNESS * 0.5)
\t\t_box("CorridorWall%d" % int(side), Vector3(Layout.WALL_THICKNESS,
\t\t\tLayout.CEILING_HEIGHT_M, block_len),
\t\t\tVector3(wall_x, Layout.CEILING_HEIGHT_M * 0.5, 0.0))
\t\tvar back_x := side * (half + Layout.CELL_DEPTH)
\t\t_box("CellBack%d" % int(side), Vector3(Layout.WALL_THICKNESS,
\t\t\tLayout.CEILING_HEIGHT_M, block_len),
\t\t\tVector3(back_x, Layout.CEILING_HEIGHT_M * 0.5, 0.0))
\t_box("Ceiling", Vector3(Layout.CORRIDOR_WIDTH_M + Layout.CELL_DEPTH * 2.0,
\t\t0.2, block_len),
\t\tVector3(0.0, Layout.CEILING_HEIGHT_M + 0.1, 0.0))

func _build_perimeter() -> void:
\tvar h := Layout.YARD_SIZE * 0.5
\tfor spec in [[Vector3(Layout.YARD_SIZE, Layout.WALL_HEIGHT,
\t\t\tLayout.WALL_THICKNESS), Vector3(0.0, Layout.WALL_HEIGHT * 0.5, -h)],
\t\t[Vector3(Layout.YARD_SIZE, Layout.WALL_HEIGHT, Layout.WALL_THICKNESS),
\t\t\tVector3(0.0, Layout.WALL_HEIGHT * 0.5, h)],
\t\t[Vector3(Layout.WALL_THICKNESS, Layout.WALL_HEIGHT, Layout.YARD_SIZE),
\t\t\tVector3(-h, Layout.WALL_HEIGHT * 0.5, 0.0)],
\t\t[Vector3(Layout.WALL_THICKNESS, Layout.WALL_HEIGHT, Layout.YARD_SIZE),
\t\t\tVector3(h, Layout.WALL_HEIGHT * 0.5, 0.0)]]:
\t\t_box("Perimeter", spec[0], spec[1])

func _build_tower(base: Vector3) -> void:
\t_box("TowerLeg", Vector3(Layout.TOWER_FOOTPRINT, Layout.TOWER_HEIGHT,
\t\tLayout.TOWER_FOOTPRINT),
\t\tbase + Vector3(0.0, Layout.TOWER_HEIGHT * 0.5, 0.0))
\t_box("TowerCab", Vector3(Layout.TOWER_FOOTPRINT + 1.4, 2.2,
\t\tLayout.TOWER_FOOTPRINT + 1.4),
\t\tbase + Vector3(0.0, Layout.TOWER_HEIGHT + 1.1, 0.0))

func _build_vent() -> void:
\t# A square shaft above the corridor: four slabs leaving a VENT_BORE_M gap.
\tvar bore := Layout.VENT_BORE_M
\tvar y := Layout.VENT_HEIGHT + bore * 0.5
\tvar length := Layout.CORRIDOR_LENGTH
\tvar t := 0.15
\t_box("VentFloor", Vector3(bore + t * 2.0, t, length),
\t\tVector3(0.0, Layout.VENT_HEIGHT - t * 0.5, 0.0))
\t_box("VentRoof", Vector3(bore + t * 2.0, t, length),
\t\tVector3(0.0, Layout.VENT_HEIGHT + bore + t * 0.5, 0.0))
\tfor side in [-1.0, 1.0]:
\t\t_box("VentWall%d" % int(side), Vector3(t, bore, length),
\t\t\tVector3(side * (bore * 0.5 + t * 0.5), y, 0.0))
'''

FILES["tools/measure.gd"] = '''extends SceneTree
# Measures the BUILT graybox with raycasts and writes studio_metrics.json.
#
# This is the evidence the phase-1 gate reads. It deliberately measures the
# geometry rather than printing Layout's constants: a constant is an
# intention, a raycast is a measurement, and the whole point of the gate is
# to catch the case where they disagree.
#
#   godot --headless --path . --script res://tools/measure.gd

const OUT := "res://studio_metrics.json"

func _initialize() -> void:
\tvar world := load("res://scenes/world.tscn").instantiate()
\tget_root().add_child(world)
\tawait physics_frame
\tawait physics_frame
\tvar space := world.get_world_3d().direct_space_state
\tvar metrics := {}
\tmetrics["corridor_width_m"] = _span(space, Vector3(0, 1.2, 0), Vector3.RIGHT)
\tmetrics["ceiling_height_m"] = _distance(space, Vector3(0, 0.05, 0), Vector3.UP)
\tvar vent_y: float = Layout.VENT_HEIGHT + Layout.VENT_BORE_M * 0.5
\tmetrics["vent_bore_m"] = _span(space, Vector3(0, vent_y, 0), Vector3.RIGHT)
\tmetrics["crouch_clearance_m"] = _distance(
\t\tspace, Vector3(0, Layout.VENT_HEIGHT + 0.02, 0), Vector3.UP)
\tmetrics["walk_speed_mps"] = Layout.WALK_SPEED_MPS
\tmetrics["sprint_speed_mps"] = Layout.SPRINT_SPEED_MPS
\tmetrics["wall_height_m"] = _distance(
\t\tspace, Vector3(0, 0.05, Layout.YARD_SIZE * 0.5), Vector3.UP)
\tvar f := FileAccess.open(OUT, FileAccess.WRITE)
\tf.store_string(JSON.stringify(metrics, "  "))
\tf.close()
\tprint("STUDIO_METRICS_OK ", JSON.stringify(metrics))
\tquit(0)

func _cast(space: PhysicsDirectSpaceState3D, from: Vector3, dir: Vector3,
\t\tmax_dist: float = 200.0) -> float:
\tvar q := PhysicsRayQueryParameters3D.create(from, from + dir * max_dist)
\tvar hit := space.intersect_ray(q)
\tif hit.is_empty():
\t\treturn -1.0
\treturn from.distance_to(hit["position"])

func _distance(space: PhysicsDirectSpaceState3D, from: Vector3,
\t\tdir: Vector3) -> float:
\treturn snappedf(_cast(space, from, dir), 0.001)

func _span(space: PhysicsDirectSpaceState3D, from: Vector3,
\t\taxis: Vector3) -> float:
\tvar a := _cast(space, from, axis)
\tvar b := _cast(space, from, -axis)
\tif a < 0.0 or b < 0.0:
\t\treturn -1.0
\treturn snappedf(a + b, 0.001)
'''

FILES["tools/assert_metrics.py"] = '''#!/usr/bin/env python3
"""Fail if the measured graybox disagrees with the target's Bucket A.

This is the phase-1 verify_cmd's second half:

    godot --headless --path . --script res://tools/measure.gd \\
      && python3 tools/assert_metrics.py

Exit code depends on the geometry being right, which is what AGENTS.md
Rule 4 means by an honest gate.
"""
import json
import sys
from pathlib import Path

TOLERANCE = 0.05

root = Path(__file__).resolve().parent.parent
target = json.loads((root / "studio_target.json").read_text())
metrics_path = root / "studio_metrics.json"
if not metrics_path.exists():
    sys.exit("studio_metrics.json not found — did measure.gd run?")
metrics = json.loads(metrics_path.read_text())

failures = []
for key, want in (target.get("bucket_a") or {}).items():
    if isinstance(want, bool) or not isinstance(want, (int, float)):
        continue
    if key not in metrics:
        failures.append(f"{key}: target {want}, NOT MEASURED")
        continue
    got = metrics[key]
    if not isinstance(got, (int, float)) or got < 0:
        failures.append(f"{key}: target {want}, measurement failed ({got})")
    elif abs(got - want) > abs(want) * TOLERANCE:
        failures.append(f"{key}: target {want}, measured {got}")

if failures:
    print("bucket A conformance FAILED:")
    for f in failures:
        print("  -", f)
    sys.exit(1)
print(f"bucket A conformance OK ({len(metrics)} metrics)")
'''

FILES["studio_target.json"] = '''{
  "_comment": "Phase 0 output. Bucket A must be NUMBERS: the gate compares them against tools/measure.gd's raycasts. Bucket B is prose: the visual judge scores it.",
  "bucket_a": {
    "corridor_width_m": 2.4,
    "ceiling_height_m": 3.0,
    "vent_bore_m": 0.7,
    "crouch_clearance_m": 0.7,
    "wall_height_m": 6.0,
    "walk_speed_mps": 2.6,
    "sprint_speed_mps": 5.4
  },
  "bucket_b": {
    "palette": "cold fluorescent white over warm rust and concrete grey",
    "light": "hard overhead fluorescents inside, low warm sun outside at dusk",
    "wear": "institutional, scuffed at hand height, clean at ceiling",
    "mood": "orderly and watched; the danger is being seen, not being hurt",
    "silhouette": "long low cell block, one tall tower breaking the roofline"
  }
}
'''

FILES["studio_protocol.json"] = '''{
  "_comment": "Published by the netcode task. The fuzz swarm reads this; see studio/qa/deepseek_fuzzer.py PROTOCOL_DOC.",
  "transport": "websocket",
  "host": "127.0.0.1",
  "port": 8910,
  "path": "/",
  "encoding": "json",
  "handshake": {"type": "join", "name": "$BOT"},
  "state_field": "players",
  "position_field": "pos",
  "move": {"type": "move", "pos": [0, 0, 0], "seq": 0},
  "privileged": [
    {"type": "open_door", "door": "block_a_gate", "clearance": 3},
    {"type": "grant_item", "item": "vent_key"}
  ],
  "bounds": {"x": [-30, 30], "y": [0, 12], "z": [-30, 30]},
  "max_speed_mps": 5.4
}
'''

FILES[".gitignore"] = '''.godot/
.import/
export_presets.cfg
studio_metrics.json
studio_render.gd
*.tmp
'''

FILES["README.md"] = '''# Prison Escape

A 3D multiplayer cops-and-robbers prison-escape game, built by the ARC studio
fleet (`ARC_FLEET=studio`).

## Where the build is

    .venv/bin/python main.py studio status prison-escape .

## The phase gate

Phase 1 is graybox: primitives only, and the dimensions must MEASURE correctly.

    godot --headless --path . --script res://tools/measure.gd
    python3 tools/assert_metrics.py

`studio_target.json` holds the target. Bucket A is numbers (checked by the
command above); Bucket B is atmosphere (scored by the visual judge).

## Layout

    scripts/layout.gd     every dimension, in one table
    scripts/world.gd      builds the graybox from that table
    tools/measure.gd      raycasts the built level, writes studio_metrics.json
    tools/assert_metrics.py  compares measurements to the target
    studio_target.json    the phase-0 target (Bucket A + Bucket B)
    studio_protocol.json  the wire contract the QA swarm fuzzes

Nothing here is authored by hand in the editor on purpose: a dimension change
is one constant plus a re-measure.
'''


def create(repo, *, project="prison-escape", force=False):
    """Write the scaffold into `repo`. Returns the relative paths written."""
    root = Path(repo).expanduser()
    root.mkdir(parents=True, exist_ok=True)
    written = []
    for rel, body in FILES.items():
        dest = root / rel
        if dest.exists() and not force:
            continue
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(body, encoding="utf-8")
        written.append(rel)
    return sorted(written)
